[Network]
Type="channel"
CAFile="sdk/ca.crt"
Cert="sdk/sdk.crt"
Key="sdk/sdk.key"

[[Network.Connection]]
NodeURL="192.168.226.143:20200"
GroupID=1

[Account]
KeyFile="account/admin_key_0x1519f11ecddba257e261902ff2a00fbd43c3bf42.pem"


[Chain]
ChainID=1
SMCrypto=false

[log]
Path="./"